# App Service

apiVersion: v1
kind: Service
metadata:
  name: my-go-app
  labels:
    app: my-go-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000 #should match the port which app is listening
  selector:
    app: my-go-app
