# App Service
#https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: my-go-app-service
#spec:
#  type: LoadBalancer
#  selector:
#    app: my-go-app
#  ports:
#  - protocol: TCP
#    port: 80
#    targetPort: 3000
spec:
  type: NodePort
  selector:
    app: my-go-app
  ports:
    - port: 80
      targetPort: 3000
