name: Get Branch Name
on:
  push:

jobs:
  branchname:
    name: get branch name
    runs-on: ubuntu-latest
    steps:
    - name: Extract image metadata
      run: |
        echo ${GITHUB_REF#refs/*/}
        REF_NAME=$(echo ${GITHUB_REF#refs/*/} | sed -e 's/^v//')
        TAG=$(printf ${REF_NAME} | tr -c '[[:alnum:]]._-' '_')
        if [[ "${REF_NAME}" == "main" || "${REF_NAME}" == "master" ]]; then TAG=latest; fi
        echo "REF_NAME=$REF_NAME"
        echo "TAG=$TAG"
