name: Get Branch Name
on:
  push:

jobs:
  branchtest:
    name: branch name test
    runs-on: ubuntu-latest
    steps:
    - name: Branch name test
      run: |
        REF_NAME=$(echo ${GITHUB_REF#refs/*/} | sed -e 's/^v//')
        TAG=$(printf ${REF_NAME} | tr -c '[[:alnum:]]._-' '_')
        if [[ "${REF_NAME}" == "main" || "${REF_NAME}" == "master" ]]; then TAG=latest; fi
        echo "TAG=$TAG" >> $GITHUB_ENV
    - name: print Tag 
      run: echo $TAG
  branchname:
    name: get branch name
    runs-on: ubuntu-latest
    steps:
    - name: Get Branch Name
      run: |
        echo ${GITHUB_REF#refs/*/}
        REF_NAME=$(echo ${GITHUB_REF#refs/*/} | sed -e 's/^v//')
        TAG=$(printf ${REF_NAME} | tr -c '[[:alnum:]]._-' '_')
        if [[ "${REF_NAME}" == "main" || "${REF_NAME}" == "master" ]]; then TAG=latest; fi
        echo "REF_NAME=$REF_NAME"
        echo "TAG=$TAG"
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
      
      
      
      
