name: Deploy images to GKE

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IMAGE: "my-go-app/app"
  GKE_CLUSTER: dpe-insights-extractor
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: my-go-app
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to deploy
        required: true
jobs:
  deploy:
    name: deploy images
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_DEPLOY_SA_KEY }}

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        sudo mv kustomize /usr/local/bin/
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      env:
        TAG: ${{ github.event.inputs.tag }}
        DEPLOYMENT_DIR: ./kubernetes/overlays/production/
      run: |
        $(cd $DEPLOYMENT_DIR && 
        kustomize edit set image gcr.io/$PROJECT_ID/$IMAGE:$TAG &&
        kustomize edit add secret go-app --from-literal=test-secret=test)
        kustomize build $DEPLOYMENT_DIR | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
