name: Job Enviroment Test 
on:
  workflow_dispatch:
env:
  JOB_ENV: 'production'
jobs:
  deploy:
    environment: 
      name: ${{ env.JOB_ENV }}
    name: deploy images
    runs-on: ubuntu-latest
    steps:
    - name: Testing job environment
      run: echo ${{ env.NAME }} | sed 's/./& /g'
        
