name: Job Enviroment Test 
on:
  workflow_dispatch:
jobs:
  set_environment:
    outputs:
      env: ${{ steps.setenv.outputs.env }}
    runs-on: ubuntu-latest
    steps:
    - id: setenv
      run: echo "::set-output name=env::production"
    
#   use_outputs_environemnt_with_object_syntax:
#     needs: set_environment
#     environment: 
#       name: ${{ needs.set_environment.outputs.env }}
#     runs-on: ubuntu-latest
#     steps:
#     - name: Testing job environment
#       run: echo ${{ secrets.NAME }} | sed 's/./& /g'
  # this doesn't work I get error 
  # The workflow is not valid. .github/workflows/job-environment-test.yml (Line: 25, Col: 18): Unrecognized named-value: 'needs'. Located at position 1 within expression: needs.set_environment.outputs.env
  use_outputs_environemnt_directly:    
    needs: set_environment
    environment: "${{ needs.set_environment.outputs.env }}"
    runs-on: ubuntu-latest
    steps:
    - name: Testing job environment
      run: echo ${{ secrets.NAME }} | sed 's/./& /g'
  
        
