name: Job Needs Test
on:
  push:
    branches:
      - '*/*'
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+\-rc[0-9]+'
jobs:
  job1-test:
    name: Job 1 
    runs-on: ubuntu-latest
    steps:
    - name: Job 1 step 1
      run: echo "Job 1"

  pick-environment:
    name: Pick environment for deployment
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: ['job1-test']
    outputs:
      env-name: ${{ steps.setenv.outputs.env-name }}
    runs-on: ubuntu-latest
    steps:
      - if: startsWith(github.ref, 'refs/tags/v')
        run: echo "APP_ENV=staging" >> $GITHUB_ENV
      - if: github.ref == 'refs/heads/main'
        run: echo "APP_ENV=dev" >> $GITHUB_ENV
      - id: setenv
        run: echo "::set-output name=env-name::${{ env.APP_ENV }}"

  job2:
    name: Job 2 
    needs: pick-environment
    runs-on: ubuntu-latest
    steps:
    - name: Job 2 step 2
      run: echo ${{ needs.pick-environment.outputs.env-name }}
         
  job3:
    needs: ['job1-test', job2]  
    name: Job 3 
    runs-on: ubuntu-latest
    steps:
    - name: Job 3 step 3
      run: echo "Job 3"       

  job4:
    needs: [job3]  
    name: Job 4
    runs-on: ubuntu-latest
    steps:
    - name: Job 4 step 4
      run: echo "Job 4"       



