name: Job Enviroment Test 
on:
  workflow_dispatch:
jobs:
  set_environment:
    outputs:
      env: ${{ steps.setenv.outputs.env }}
    runs-on: ubuntu-latest
    steps:
    - id: setenv
      run: echo "::set-output name=env::production"
    
  use_outputs_environemnt:
    needs: set_environment
    environment: 
      name: ${{ needs.set_environment.outputs.env }}
    runs-on: ubuntu-latest
    steps:
    - name: Testing job environment
      run: echo ${{ secrets.NAME }} | sed 's/./& /g'
        
