name: Job Enviroment Test 
on:
  workflow_dispatch:
env:
  JOB_ENV: 'production'
jobs:
  deploy:
    environment: ${{env.JOB_ENV}}
    name: deploy images
    runs-on: ubuntu-latest
    steps:
    - name: Testing job environment
      run: echo ${{ secrets.NAME }} | sed 's/./& /g'
        
