name: Build and push image to google container registry for go app

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IMAGE: "my-go-app/app"
  TAG: ${{ github.event.release.tag_name }} #"latest"
on:
  push:
    branches:
      - '*/*'
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+\-rc[0-9]+'
jobs:
  backend:
    name: Setup, Build, Publish go app
    runs-on: ubuntu-18.04
    steps:
    - name: event name
      run: |
        echo ${{ github.event_name }} 
        echo ${{ github.ref }}
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get Tag
      #if: ${{ !env.ACT }}
      run: |
        echo "TAG=$(echo $TAG | sed -e 's/^v//')" >> $GITHUB_ENV
#     - name: Set up Cloud SDK
#       uses: google-github-actions/setup-gcloud@master
#       with:
#         service_account_key: ${{ secrets.GKE_DEPLOY_SA_KEY }}
#     # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
#     - run: |-
#         gcloud --quiet auth configure-docker

#     # Build the Go App Docker image
#     - name: Build Go App
#       run: |-
#         docker build \
#           --tag "gcr.io/$PROJECT_ID/$IMAGE:${{env.TAG}}" \
#           --build-arg GITHUB_SHA="$GITHUB_SHA" \
#           --build-arg GITHUB_REF="$GITHUB_REF" \
#           .
#     # Push the Docker images to Google Container Registry
#     - name: Publish images to google container registry
#       run: |-
#         docker push "gcr.io/$PROJECT_ID/$IMAGE:${{env.TAG}}"
