name: SED - FIND & REPLACE
on:
  push:
    branches:
      - domain/*

jobs:
  branchtest:
    name: sed command test to replace text in file
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        HOST=$( echo ${GITHUB_REF#refs/*/*/} | cut -d- -f1 )
        sed -i 's/{USER}/$HOST/g' kubernetes/overlays/staging/ingress_patch.json
        cat kubernetes/overlays/staging/ingress_patch.json
        
