name: SED 
on:
  push:
    branches:
      - domain/*

jobs:
  branchtest:
    name: sed command test to replace text in file
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        sed -i 's/{USER}/${{env.USER}}/g' kubernetes/overlays/staging/ingress_patch.json
        cat kubernetes/overlays/staging/ingress_patch.json
      env:
        USER: ${{ github.actor }}
        
