name: Test

env:
  IMAGES: |
    abc
    def
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:    
  getenv:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${GITHUB_REF#refs/heads/}"
  deploy:
    environment: Test
    name: deploy images
    runs-on: ubuntu-latest
    steps:
    - name: kustomize version
      run: kustomize version
    - name: secret env test
      run: echo ${{ secrets.STAGING_D_GC_DOCKER_HUB_ACCESS_TOKEN }}
    - name: Test
      run: |
        if [[ -n "$IMAGES" ]]; then
          echo "Setting image: $IMAGES"
        fi
