name: Test

env:
  IMAGES: |
    abc
    def
 
on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy images
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        if [[ -n "$IMAGES" ]]; then
          echo "Setting image: $IMAGES"
        fi
