name: Test

env:
  IMAGES: |
    abc
    def
 
on:
  workflow_dispatch:

jobs:     
  deploy:
    environment: Test
    name: deploy images
    runs-on: ubuntu-latest
    steps:
    - name: secret env test
      run: echo ${{secrets.TEST2}}
    - name: Test
      run: |
        if [[ -n "$IMAGES" ]]; then
          echo "Setting image: $IMAGES"
        fi
